id: AB45C4CE4
title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
type: translation
pechas:
- IF427A6E1
- I2E325111
- I342147D4
- I98000FF4
- IDBBD3BDF
- I7B8F5DD6
- IE88EB74E
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:27.665621
  last_modified_at: 2023-01-04 11:54:27.665628
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IF427A6E1/DE30: 4A18
  I2E325111/49B0: 4A18
  I342147D4/CBC3: 4A18
  I98000FF4/EE41: 4A18
  IDBBD3BDF/B1C7: 4A18
  I7B8F5DD6/7FAC: 4A18
  IE88EB74E/CEE0: 4A18
